-- MySQL Script generated by MySQL Workbench
-- Tue 23 Feb 2016 03:37:49 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nearby
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nearby
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nearby` DEFAULT CHARACTER SET utf8 ;
USE `nearby` ;

-- -----------------------------------------------------
-- Table `nearby`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `clientID` VARCHAR(245) NULL,
  `accessToken` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
